modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="yeet_a_brick"
version="1.0.0"
displayName="Yeet-ABrick"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="arnav, MCreator"

[[dependencies.yeet_a_brick]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




